In [1]:
from Game import *
import pandas as pd

%load_ext autoreload
%autoreload 2

In [2]:
week = Game('FanDuel-NFL-2022 ET-12 ET-11 ET-84373-players-list.csv',
            'NFL',
            '2022-14 Fantasy Pros Projections 22-12-10.xlsx',
            'FantasyPros NFL Historical.xlsx',
            2022, 14)

In [3]:
DROP = ['Denver Broncos', 'New York Jets', 'Cleveland Browns', 'New York Giants'] # NFL

week.generateRosters('reimagined', drop_players_initial=DROP, drop_injuries=['D', 'IR', 'O'])

Preprocessing completed in 0:00:00.002505.

Beginning strategy: reimagined
--------------------------------------------------

Initial iteration completed in 0:00:39.785732.
Optimal solutions: 511 / 511

Dropped Justin Jefferson. Using Roster1 as basis...
Iteration 1 completed in 0:00:43.156772.
Optimal solutions: 511 / 511

Dropped Jalen Hurts. Using Roster2 as basis...
Iteration 2 completed in 0:00:42.472465.
Optimal solutions: 511 / 511

Dropped Tony Pollard. Using Roster3 as basis...
Iteration 3 completed in 0:00:43.361865.
Optimal solutions: 511 / 511

Dropped Garrett Wilson. Using Roster4 as basis...
Iteration 4 completed in 0:00:39.109950.
Optimal solutions: 511 / 511

Dropped Dameon Pierce. Using Roster5 as basis...
Iteration 5 completed in 0:00:47.389306.
Optimal solutions: 511 / 511

Dropped Jerry Jeudy. Using Roster6 as basis...
Iteration 6 completed in 0:00:45.241947.
Optimal solutions: 511 / 511

Dropped Pat Freiermuth. Using Roster7 as basis...
Iteration 7 completed in 0:00:45.437198.
Optimal solutions: 511 / 511

Dropped Greg Dulcich. Using Roster8 as basis...
Iteration 8 completed in 0:00:47.932423.
Optimal solutions: 511 / 511

Dropped Detroit Lions. Using Roster9 as basis...
Iteration 9 completed in 0:00:45.628832.
Optimal solutions: 511 / 511
--------------------------------------------------

Strategy completed in 0:07:19.518494.
Optimal results: 5111 / 5111

Summarizing rosters...
Rosters summarized in 0:00:13.256704.

Total time: 0:07:32.777703.

(5111, 5111)

In [4]:
# verify dropped players
week.tracking['preprocessing_drops'].sort_values('Projected', ascending=False).head(10)

,Nickname,Position,Salary,Injury Indicator,QB,RB,WR,TE,DST,FLEX,Projected,MR_Period,MR_Season,MR_WeekNum,N_Games,Hist_Avg,Hist_Std,Proj_Percent
604,New York Jets,D,4000,NaN,0,0,0,0,1,0,6.2,2022-13,2022.0,13.0,16.0,7.44,5.07,25.1
663,Cleveland Browns,D,3300,NaN,0,0,0,0,1,0,6.1,2022-13,2022.0,13.0,16.0,5.50,7.06,51.2
664,Denver Broncos,D,3200,NaN,0,0,0,0,1,0,5.8,2022-13,2022.0,13.0,16.0,5.75,4.86,28.3
661,New York Giants,D,3500,NaN,0,0,0,0,1,0,5.6,2022-13,2022.0,13.0,16.0,4.94,4.12,8.7
306,Jameson Williams,WR,4500,NaN,0,0,1,0,0,1,5.0,2022-13,2022.0,13.0,1.0,0.00,NaN,37.1
282,Montrell Washington,WR,4600,NaN,0,0,1,0,0,1,2.9,2022-13,2022.0,13.0,12.0,0.27,0.80,0.3
233,Jalen Reagor,WR,4800,NaN,0,0,1,0,0,1,2.8,2022-13,2022.0,13.0,16.0,2.09,2.51,0.1
297,Brevin Jordan,TE,4600,NaN,0,0,0,1,0,1,2.8,2022-13,2022.0,13.0,14.0,4.19,4.12,0.8
295,Amari Rodgers,WR,4600,NaN,0,0,1,0,0,1,2.8,2022-10,2022.0,10.0,16.0,0.25,1.00,0.2
127,J.K. Dobbins,RB,6000,NaN,0,1,0,0,0,1,2.8,2022-06,2022.0,6.0,16.0,10.08,7.83,85.4

In [5]:
top = week.selectRosters(.75)
week._selection

'Roster4129'

In [6]:
# players with appearances
x = week.data[['Nickname', 'Position', 'Salary', 'Projected', 'Top Appearances']]
x[x['Top Appearances'] > 0].sort_values('Top Appearances', ascending=False)

                     Nickname Position  Salary  Projected  Top Appearances
0            Justin Jefferson       WR    9300       21.5             1310
175              Greg Dulcich       TE    5400        8.9             1135
27               Tony Pollard       RB    7500       15.1             1040
149            Pat Freiermuth       TE    5800        9.7              895
61              Dameon Pierce       RB    6500       11.7              885
6                 Jalen Hurts       QB    8700       23.6              780
665             Detroit Lions        D    3100        6.0              751
77                 Gabe Davis       WR    6200       10.1              688
33             Garrett Wilson       WR    7200       13.0              668
34              D'Andre Swift       RB    7200       13.2              585
176               Julio Jones       WR    5400        7.3              499
63                Jerry Jeudy       WR    6500       10.7              482
185            Dallas Cowboys        D    5200       12.1              454
4                  Josh Allen       QB    8700       23.1              321
198               Evan Engram       TE    5100        6.7              237
197            Kendall Hinton       WR    5100        6.2              187
36              Miles Sanders       RB    7100       12.6              171
10        Christian McCaffrey       RB    8500       16.9              162
38                 Jared Goff       QB    7100       18.3              151
658       Pittsburgh Steelers        D    3800        7.5              103
57        JuJu Smith-Schuster       WR    6600       10.8               65
13                 Joe Burrow       QB    8300       21.5               58
172           Jerick McKinnon       RB    5400        7.1               42
41              DeVonta Smith       WR    7000       11.9               19
60             T.J. Hockenson       TE    6500       10.8               18
54               Najee Harris       RB    6700       11.1               16
150  Marquez Valdes-Scantling       WR    5800        7.9               10
154               Corey Davis       WR    5700        7.5                8
49               Mark Andrews       TE    6800       11.4                7
7           Amon-Ra St. Brown       WR    8600       16.4                7
79            Latavius Murray       RB    6200        9.6                6
16               Travis Kelce       TE    8000       15.2                5
112            Michael Gallup       WR    6000        8.4                5
9                Stefon Diggs       WR    8500       16.2                4
159            Devin Duvernay       WR    5600        7.4                3
207         Dontrell Hilliard       RB    5000        6.0                3
257              Jordan Akins       TE    4700        5.1                3
217        Phillip Dorsett II       WR    4900        5.3                2
91                 James Cook       RB    6100        8.9                2
662      Jacksonville Jaguars        D    3400        5.8                2
229          Daniel Bellinger       TE    4800        5.4                1

In [7]:
# highest scoring rosters and frequency
y = top.copy()
y['Roster'] = y.index
y_g = y.groupby('Score', as_index=False).agg({'Roster':'first', 'Salary':'first', 'Projected':'first', 'Hist_Std':'first', 'K':min, 'Score':['first', 'count']})
y_g.sort_values(('Score', 'first'), ascending=False).head(10)

        Roster   Salary Projected Hist_Std    K Score
         first    first     first    first  min first count
87  Roster4129  59700.0     119.6    21.38  2.0  8152     2
86     Roster0  60000.0     120.2    20.60  0.0  7946    42
85     Roster4  60000.0     120.0    21.07  1.0  7686    61
84     Roster2  60000.0     119.7    20.23  1.0  7487    49
83    Roster37  60000.0     118.7    21.93  2.0  7456    19
82  Roster4216  60000.0     119.4    21.74  3.0  7403     2
81     Roster7  60000.0     119.2    21.06  1.0  7341    62
80   Roster531  59900.0     119.0    21.45  2.0  7283    14
79     Roster5  59900.0     119.1    20.69  1.0  7260    36
78  Roster4335  60000.0     118.8    21.63  4.0  7259     1

In [15]:
week.data[week.data['Roster4129']==1].iloc[:, :17]

,Nickname,Position,Salary,Injury Indicator,QB,RB,WR,TE,DST,FLEX,Projected,MR_Period,MR_Season,MR_WeekNum,N_Games,Hist_Avg,Hist_Std
0,Justin Jefferson,WR,9300,NaN,0,0,1,0,0,1,21.5,2022-13,2022.0,13.0,16.0,17.26,9.22
6,Jalen Hurts,QB,8700,NaN,1,0,0,0,0,0,23.6,2022-13,2022.0,13.0,16.0,23.48,7.28
27,Tony Pollard,RB,7500,NaN,0,1,0,0,0,1,15.1,2022-13,2022.0,13.0,16.0,13.84,9.79
33,Garrett Wilson,WR,7200,NaN,0,0,1,0,0,1,13.0,2022-13,2022.0,13.0,12.0,10.99,8.59
61,Dameon Pierce,RB,6500,NaN,0,1,0,0,0,1,11.7,2022-13,2022.0,13.0,12.0,11.63,6.29
77,Gabe Davis,WR,6200,NaN,0,0,1,0,0,1,10.1,2022-13,2022.0,13.0,16.0,11.04,7.91
149,Pat Freiermuth,TE,5800,NaN,0,0,0,1,0,1,9.7,2022-13,2022.0,13.0,16.0,7.86,2.97
175,Greg Dulcich,TE,5400,NaN,0,0,0,1,0,1,8.9,2022-13,2022.0,13.0,7.0,7.20,4.31
665,Detroit Lions,D,3100,NaN,0,0,0,0,1,0,6.0,2022-13,2022.0,13.0,16.0,4.94,4.48

In [16]:
week.data[week.data['Roster0']==1].iloc[:, :17]

,Nickname,Position,Salary,Injury Indicator,QB,RB,WR,TE,DST,FLEX,Projected,MR_Period,MR_Season,MR_WeekNum,N_Games,Hist_Avg,Hist_Std
0,Justin Jefferson,WR,9300,NaN,0,0,1,0,0,1,21.5,2022-13,2022.0,13.0,16.0,17.26,9.22
6,Jalen Hurts,QB,8700,NaN,1,0,0,0,0,0,23.6,2022-13,2022.0,13.0,16.0,23.48,7.28
27,Tony Pollard,RB,7500,NaN,0,1,0,0,0,1,15.1,2022-13,2022.0,13.0,16.0,13.84,9.79
33,Garrett Wilson,WR,7200,NaN,0,0,1,0,0,1,13.0,2022-13,2022.0,13.0,12.0,10.99,8.59
61,Dameon Pierce,RB,6500,NaN,0,1,0,0,0,1,11.7,2022-13,2022.0,13.0,12.0,11.63,6.29
63,Jerry Jeudy,WR,6500,NaN,0,0,1,0,0,1,10.7,2022-13,2022.0,13.0,16.0,7.40,5.44
149,Pat Freiermuth,TE,5800,NaN,0,0,0,1,0,1,9.7,2022-13,2022.0,13.0,16.0,7.86,2.97
175,Greg Dulcich,TE,5400,NaN,0,0,0,1,0,1,8.9,2022-13,2022.0,13.0,7.0,7.20,4.31
665,Detroit Lions,D,3100,NaN,0,0,0,0,1,0,6.0,2022-13,2022.0,13.0,16.0,4.94,4.48

In [17]:
week.data[week.data['Roster4']==1].iloc[:, :17]

,Nickname,Position,Salary,Injury Indicator,QB,RB,WR,TE,DST,FLEX,Projected,MR_Period,MR_Season,MR_WeekNum,N_Games,Hist_Avg,Hist_Std
0,Justin Jefferson,WR,9300,NaN,0,0,1,0,0,1,21.5,2022-13,2022.0,13.0,16.0,17.26,9.22
6,Jalen Hurts,QB,8700,NaN,1,0,0,0,0,0,23.6,2022-13,2022.0,13.0,16.0,23.48,7.28
27,Tony Pollard,RB,7500,NaN,0,1,0,0,0,1,15.1,2022-13,2022.0,13.0,16.0,13.84,9.79
61,Dameon Pierce,RB,6500,NaN,0,1,0,0,0,1,11.7,2022-13,2022.0,13.0,12.0,11.63,6.29
77,Gabe Davis,WR,6200,NaN,0,0,1,0,0,1,10.1,2022-13,2022.0,13.0,16.0,11.04,7.91
149,Pat Freiermuth,TE,5800,NaN,0,0,0,1,0,1,9.7,2022-13,2022.0,13.0,16.0,7.86,2.97
175,Greg Dulcich,TE,5400,NaN,0,0,0,1,0,1,8.9,2022-13,2022.0,13.0,7.0,7.20,4.31
176,Julio Jones,WR,5400,NaN,0,0,1,0,0,1,7.3,2022-13,2022.0,13.0,16.0,6.80,4.64
185,Dallas Cowboys,D,5200,NaN,0,0,0,0,1,0,12.1,2022-13,2022.0,13.0,16.0,11.44,7.69

## Save Game

In [18]:
week.export_game()

True

## FanDuel Tournament Export File

In [12]:
play = y_g.sort_values(('Score', 'first'), ascending=False).head(16)

rosters = play[('Roster', 'first')].to_list()

play

        Roster   Salary Projected Hist_Std    K Score
         first    first     first    first  min first count
87  Roster4129  59700.0     119.6    21.38  2.0  8152     2
86     Roster0  60000.0     120.2    20.60  0.0  7946    42
85     Roster4  60000.0     120.0    21.07  1.0  7686    61
84     Roster2  60000.0     119.7    20.23  1.0  7487    49
83    Roster37  60000.0     118.7    21.93  2.0  7456    19
82  Roster4216  60000.0     119.4    21.74  3.0  7403     2
81     Roster7  60000.0     119.2    21.06  1.0  7341    62
80   Roster531  59900.0     119.0    21.45  2.0  7283    14
79     Roster5  59900.0     119.1    20.69  1.0  7260    36
78  Roster4335  60000.0     118.8    21.63  4.0  7259     1
77   Roster712  59800.0     118.9    20.82  4.0  7249     1
76     Roster8  60000.0     118.8    20.10  1.0  7227    77
75   Roster631  60000.0     118.9    20.87  3.0  7174     4
74   Roster544  60000.0     119.5    19.92  2.0  7168    16
73    Roster20  60000.0     119.0    22.05  2.0  7130    28
72     Roster3  60000.0     119.1    19.49  1.0  7088    34

In [1]:
csv = week.FanDuelCSVExport(rosters)

NameError: name 'week' is not defined

In [2]:
week.data[week.data['Roster2667']==1]

NameError: name 'week' is not defined